import Head from "next/head"
import React from "react"
import Navbar from "../navbar"

interface Props {
  children: JSX.Element
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <div className="flex h-screen w-screen select-none bg-white text-slate-400 dark:bg-gray-800 dark:text-white">
      <Head>
        <title>Interview RÖszTI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-1 pt-14 pb-2">{children}</div>
      <Navbar />
    </div>
  )
}

export default Layout
